version: '3.8'

services:
  app:
    image: macarious25siv/orange:app
    container_name: django_app
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    networks:
      - app_network

  mysql:
    image: macarious25siv/orange:mysql
    container_name: mysql_db
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
