version: '3.8'

services:
  mysql:
    image: macarious25siv/orange:mysql
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql  # Add this line to persist data

  app:
    image: macarious25siv/orange:app
    container_name: django
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    networks:
      - app_network
    command: ["sh", "-c", "sleep 45 && python manage.py runserver 0.0.0.0:8000"]

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:  # Define the volume here




# docker-compose--build
# docker-compose up
# docker-compose down
