apiVersion: v1
kind: Namespace
metadata:
  name: macarious
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: macarious
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: macarious25siv/orange:mysql
        ports:
        - containerPort: 3306
        
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: macarious
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: macarious
  labels:
    app: bookmanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orangeapp
  template:
    metadata:
      labels:
        app: orangeapp
    spec:
      containers:
      - name: orangeapp
        image: macarious25siv/orange:appK8s
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: macarious
spec:
  selector:
    app: orangeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30036
  type: NodePort



