pipeline {
    agent any
    environment {
        ANSIBLE_PRIVATE_KEY = credentials('managed_private_key') // Use Jenkins credential
    }
    stages {
        stage('check_ansible_version') {
            steps {
                sh 'ansible --version'
            }
        }
        stage('test_ssh_connectivity') {
            steps {
                script {
                    dir('Ansible/') {
                        echo "Private key content: ${ANSIBLE_PRIVATE_KEY}" 
                        // Write the private key to a temporary file
                        writeFile(file: '/tmp/ansible_private_key', text: ANSIBLE_PRIVATE_KEY)

                        // Ensure the private key file has the correct permissions
                        sh 'chmod 600 /tmp/ansible_private_key'

                        // Test SSH connectivity to the target using the private key
                        sh '''
                            echo "Testing SSH connectivity to the target..."
                            ssh -i /tmp/ansible_private_key -o StrictHostKeyChecking=no vagrant@192.168.1.201 "echo 'SSH successful!'"
                        '''
                        
                        // Optionally remove the private key after use for security
                        sh 'rm -f /tmp/ansible_private_key'
                    }
                }
            }
        }
        stage('ansible_playbook') {
            steps {
                script {
                    dir('Ansible/') {
                        // Run the Ansible playbook
                        sh 'ansible-playbook -i Inventory/inventory.ini --private-key=/tmp/ansible_private_key Playbooks/ping_check.yml'
                    }
                }
            }
        }
    }
}
