---
- name: Install Docker, reboot, and deploy container
  hosts: target_group
  become: true
  vars:
    docker_image: "macarious25siv/books:latest"
    docker_container_name: "books_container"
    docker_container_port: "8000"

  tasks:
    - name: Check if Docker is installed
      ansible.builtin.command:
        cmd: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Inform if Docker is not installed
      ansible.builtin.debug:
        msg: "Docker is not installed. Installing now..."
      when: docker_installed.failed

    - name: Pull Docker image using shell command
      ansible.builtin.shell:
        cmd: docker pull {{ docker_image }}
      when: docker_installed.rc == 0

    - name: Run Docker container
      ansible.builtin.shell:
        cmd: docker run -d --name {{ docker_container_name }} -p {{ docker_container_port }}:8000 {{ docker_image }}
      when: docker_installed.rc == 0
