apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: macarious
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orangeapp
  template:
    metadata:
      labels:
        app: orangeapp
    spec:
      containers:
      - name: orangeapp
        image: macarious25siv/orange:appK8s
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: secret_key
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: macarious
spec:
  selector:
    app: orangeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30036
  type: NodePort
