apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: macarious
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data/mysql  

