
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-Checker-binding
  namespace: macarious
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-Checker
subjects:
- kind: ServiceAccount
  name: default
  namespace: macarious
