version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false  # Disable security if you don't need authentication or SSL
      - xpack.security.http.ssl.enabled=false  # Disable SSL for HTTP communication
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"  # HTTP port
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044" # For log ingestion
      - "9600:9600" # For monitoring Logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"  # HTTP port
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Use HTTP
      - SERVER_SSL_ENABLED=false  # Disable SSL in Kibana
    networks:
      - elk

  django-app:
    image: macarious25siv/orange:appELK  # Replace with the correct image name for your Django app
    container_name: django-app
    ports:
      - "8000:8000"  # Expose Django app on port 8000
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - elk

volumes:
  elasticsearch_data:

networks:
  elk:
    driver: bridge
