version: '3.8'

services:
  nginx-proxy:
    image: proxy
    container_name: proxy
    build: .
    ports:
      - "80:80"
    networks:
      - web-network
    depends_on:
      - web

  web:
    image: macarious25siv/books:latest  # Replace with your web service image
    container_name: web
    networks:
      - web-network
    expose:
      - "8000"  # Expose the port for communication within the Docker network

networks:
  web-network:
    driver: bridge
